name: Publish to Apple Store
on: workflow_dispatch

env:
  # these are needed by fastlane
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  FLUTTER_ROOT: /home/vagrant/build/org.mindshub.insigno/submodules/flutter

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Import code signing certificate
        uses: apple-actions/import-codesign-certs@v2
        with:
          keychain: "signing_temp"
          create-keychain: "true"
          keychain-password: "password"
          p12-file-base64: ${{ secrets.IOS_CERTIFICATE_P12_BASE64 }}
          p12-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
      - name: Clone repository
        # not using actions/checkout because it does not clone `.git`, required for Flutter
        run: |
          git clone --recurse-submodules "https://github.com/${{ github.repository }}.git" .
      - name: Setup Fastlane
        run: |
          sudo apt install ruby ruby-dev
          sudo gem install bundler
          cp Gemfile Gemfile.lock ios/
          cd ios
          sudo bundle install
      - name: Extract version and version code
        run: |
          echo "VERSION=$(sed -nE 's~^version: ?([^\+]+)\+(.*)$~\1~p' pubspec.yaml)" >> $GITHUB_ENV
          VERSION_CODE=$(sed -nE 's~^version: ?([^\+]+)\+(.*)$~\2~p' pubspec.yaml)
          echo "VERCODE_1=$(( $VERSION_CODE * 10 + 1 ))" >> $GITHUB_ENV
          echo "VERCODE_2=$(( $VERSION_CODE * 10 + 2 ))" >> $GITHUB_ENV
          echo "VERCODE_3=$(( $VERSION_CODE * 10 + 3 ))" >> $GITHUB_ENV
      - name: Print some information
        run: |
          echo "Version: ${{ env.VERSION }}"
          echo "Version codes: ${{ env.VERCODE_1 }}, ${{ env.VERCODE_2 }}, ${{ env.VERCODE_3 }}"
          echo "Build directory: $BUILD_DIR"
      - name: Setup flutter
        run: |
          submodules/flutter/bin/flutter config --no-analytics
          submodules/flutter/bin/flutter pub get
      - name: Build ios app
        run: |
          submodules/flutter/bin/flutter build ios --release --no-codesign --build-number=${{ env.VERCODE_3 }} --build-name=${{ env.VERSION }}
      - name: Copy Fastlane metadata to correct directory
        run: |
          cp -r fastlane/ ios/
      - name: Run Fastlane to publish to Apple Store and update metadata
        run: |
          bundle exec fastlane run build_app skip_build_archive:true archive_path:"../build/ios/archive/Runner.xcarchive"
          bundle exec fastlane run upload_to_app_store release_status:"draft" json_key:"play_config.json" aab:"../build/app/outputs/bundle/release/app-release.aab" package_name:"org.mindshub.insigno"
